version: "3"
services:
  db:
    image: postgres:12.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
  project:
    depends_on:
      - db
    build: ./scripts/docker/anaconda-project
    working_dir: /usr/src
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./:/usr/src
      - conda:/usr/src/envs
    ports:
      - 8000:8000
    command: tail -f /dev/null
  selenium-chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
  selenium-firefox:
    image: selenium/standalone-firefox-debug
    ports:
      - 4445:4445
      - 5900:5900
volumes:
  db:
  conda:
