""" Initial model migrations.
    Generated by Django 3.1.3 on 2020-11-15 22:48
"""

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions

import ProjectTime.project.mixins

class Migration(migrations.Migration):
    """ Django migration class for initial migrations
    """
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    help_text='*Required: Enter a unique name for the project (255 characters max).',
                    max_length=255,
                    unique=True
                )),
                ('active', models.BooleanField(
                    blank=True,
                    default=True,
                    help_text='An inactive project is disabled for modification.'
                )),
            ],
            bases=(models.Model, ProjectTime.project.mixins.ValidateModelMixin),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('start_time', models.DateTimeField(
                    help_text='*Required: Enter the date and time that chargeable work began on.'
                )),
                ('end_time', models.DateTimeField(
                    blank=True,
                    help_text='Enter the date and time that chargeable work ended on.',
                    null=True
                )),
                ('closed', models.BooleanField(
                    blank=True,
                    default=False,
                    help_text='A closed charge is disabled for modification.'
                )),
                ('project', models.ForeignKey(
                    help_text='*Required: Select the project this charge will be associated with.',
                    on_delete=django.db.models.deletion.PROTECT,
                    to='project.project'
                )),
            ],
            options={
                'get_latest_by': ('start_time',),
            },
            bases=(models.Model, ProjectTime.project.mixins.ValidateModelMixin),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(
                check=models.Q(end_time__gte=django.db.models.expressions.F('start_time')),
                name='end_time_must_be_on_or_after_start_time'
            ),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(
                check=models.Q(('closed__exact', True), ('end_time__exact', None), _negated=True),
                name='cannot_close_without_end_time'
            ),
        ),
    ]
