# Generated by Django 2.2.1 on 2019-07-14 16:17

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(check=models.Q(start_time__lte=django.db.models.expressions.F('end_time')), name='start_time_less_than_end_time'),
        ),
    ]
