# Generated by Django 3.2.4 on 2021-06-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210529_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'get_latest_by': ('start_time',), 'verbose_name': 'time increment'},
        ),
        migrations.AlterField(
            model_name='charge',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Enter the date and time that work ended on.', null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='project',
            field=models.ForeignKey(help_text='*Required: Select the project this time increment will be associated with.', on_delete=django.db.models.deletion.PROTECT, to='project.project'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='start_time',
            field=models.DateTimeField(help_text='*Required: Enter the date and time that work began on.'),
        ),
    ]
