# Generated by Django 2.2.1 on 2019-09-08 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190908_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'get_latest_by': ('start_time',),
                     'ordering': ('start_time',)},
        ),
    ]
