# Generated by Django 2.2.1 on 2019-09-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_charge_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='closed',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='A closed charge is disabled for modification.'
            ),
        ),
        migrations.AlterField(
            model_name='charge',
            name='end_time',
            field=models.DateTimeField(
                blank=True,
                help_text='Enter the date and time that chargeable work ended on.',
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='charge',
            name='project',
            field=models.ForeignKey(
                help_text='*Required: Select the project this charge will be associated with.',
                on_delete=django.db.models.deletion.PROTECT,
                to='project.Project'
            ),
        ),
        migrations.AlterField(
            model_name='charge',
            name='start_time',
            field=models.DateTimeField(
                help_text='*Required: Enter the date and time that chargeable work began on.'
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(
                help_text='*Required: Enter a unique name for the project (255 characters max).',
                max_length=255,
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(
                blank=True,
                help_text='Enter the date and time at which the task is to be done.',
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='A completed task is disabled for modification.'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(
                help_text='*Required: Select the project this task will be associated with.',
                on_delete=django.db.models.deletion.PROTECT,
                to='project.Project'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(
                help_text='*Required: Enter the task that is to be done (255 characters max).',
                max_length=255
            ),
        ),
    ]
