# Generated by Django 3.0.8 on 2020-07-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20190922_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'get_latest_by': ('start_time',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
