version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.0.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - browser-tools/install-firefox: # https://github.com/CircleCI-Public/browser-tools-orb/issues/14
          version: "78.0"
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda_installer.sh
      - run: bash miniconda_installer.sh -b -p $HOME/miniconda
      - run: echo "export PATH=$HOME/miniconda/bin:$PATH" >> $BASH_ENV
      - run: conda config --set always_yes yes --set changeps1 no
      - run: conda update -q conda
      - run: conda info -a
      - run: conda install anaconda-project
      - run: anaconda-project prepare --env-spec lint
      - run: anaconda-project prepare --env-spec database
      - run: anaconda-project prepare --env-spec application
      - run: anaconda-project prepare --env-spec test-acceptance
      - run: anaconda-project run pylint src/ProjectTime --fail-under 7
      - run: anaconda-project run pg_ctl initdb
      - run:
          command: anaconda-project run postgres
          background: true
      - run: sleep 10
      - run: anaconda-project run manage.py test
      - run:
          command: anaconda-project run manage.py testserver --addrport 8000 --noinput ../../test/fixtures/admin_user.json
          background: true
      - run: sleep 10
      - run: anaconda-project run robot -v SERVER_PORT:8000 -d smoke_test_artifacts test/suites/smoke_tests.robot
      - run: anaconda-project run robot -v SERVER_PORT:8000 -d workflow_test_artifacts test/suites/workflow_tests.robot
      - run: anaconda-project run setup.py sdist bdist_wheel
      - run: anaconda-project run conda build conda-recipe
