version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y firefox
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda_installer.sh
      - run: bash miniconda_installer.sh -b -p $HOME/miniconda
      - run: PATH="$HOME/miniconda/bin:$PATH" conda config --set always_yes yes --set changeps1 no
      - run: PATH="$HOME/miniconda/bin:$PATH" conda update -q conda
      - run: PATH="$HOME/miniconda/bin:$PATH" conda info -a
      - run: PATH="$HOME/miniconda/bin:$PATH" conda install anaconda-project
      - run: PATH="$HOME/miniconda/bin:$PATH" anaconda-project prepare --env-spec database
      - run: PATH="$HOME/miniconda/bin:$PATH" anaconda-project prepare --env-spec application
      - run: PATH="$HOME/miniconda/bin:$PATH" anaconda-project prepare --env-spec test-acceptance
      - run: PATH="$HOME/miniconda/bin:$PATH" anaconda-project run pg_ctl initdb
      - run:
          command: |
            PATH="$HOME/miniconda/bin:$PATH" anaconda-project run postgres &
            PATH="$HOME/miniconda/bin:$PATH" sleep 10
            PATH="$HOME/miniconda/bin:$PATH" anaconda-project run manage.py test
      - run:
          command: |
            PATH="$HOME/miniconda/bin:$PATH" anaconda-project run postgres &
            PATH="$HOME/miniconda/bin:$PATH" sleep 10
            PATH="$HOME/miniconda/bin:$PATH" anaconda-project run robot -d smoke_test_artifacts test/suites/smoke_tests.robot
            PATH="$HOME/miniconda/bin:$PATH" anaconda-project run robot -d workflow_test_artifacts test/suites/workflow_tests.robot
      - run: PATH="$HOME/miniconda/bin:$PATH" anaconda-project run setup.py sdist bdist_wheel
      - run: PATH="$HOME/miniconda/bin:$PATH" anaconda-project run conda build conda-recipe