version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run: sudo apt install firefox
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda_installer.sh
      - run: bash miniconda_installer.sh -b -p $HOME/miniconda
      - run: export PATH="$HOME/miniconda/bin:$PATH"
      - run: conda config --set always_yes yes --set changeps1 no
      - run: conda update -q conda
      - run: conda info -a
      - run: conda install anaconda-project
      - run: anaconda-project prepare --env-spec database
      - run: anaconda-project prepare --env-spec application
      - run: anaconda-project prepare --env-spec test-acceptance
      - run: anaconda-project run pg_ctl initdb
      - run: anaconda-project run postgres &
      - run: sleep 10
      - run: anaconda-project run manage.py test
      - run: anaconda-project run robot -d smoke_test_artifacts test/suites/smoke_tests.robot
      - run: anaconda-project run robot -d workflow_test_artifacts test/suites/workflow_tests.robot
      - run: anaconda-project run setup.py sdist bdist_wheel
      - run: anaconda-project run conda build conda-recipe