# Generated by Django 2.2.1 on 2019-09-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190908_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='closed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
