{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name').lower() }}
  version: {{ data.get('version') }}

source:
  path: ../dist/ProjectTime-{{ data.get('version') }}.tar.gz

build:
  noarch: python
  script: "$PYTHON -m pip install ProjectTime-$PKG_VERSION.tar.gz"

requirements:
  host:
    - python >=3.8,<3.9
    - pip
    - setuptools

  run:
    - python >=3.8,<3.9
    - psycopg2 >=2.8,<2.9
    - sqlparse >=0.4,<0.5
    - pytz=2019.3
    - django >=3.2,<3.3
    - pandas >=1.2,<1.3
    - bokeh >=2.3,<2.4

test:
  imports:
    - {{ data.get('name') }}

about:
  home: {{ data.get('url') }}
  summary: {{ data.get('description') }}
