# Generated by Django 2.2.1 on 2019-08-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
    ]
