# Generated by Django 2.2.1 on 2019-09-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
